services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"
  golang:
    image: supertikuwa/air:latest
    working_dir: /app
    volumes:
      - ../backend:/app
    ports:
      - "10080:8080"
